repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: check-yaml
          - id: check-toml
          - id: check-json
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: mixed-line-ending
            args: [--fix=lf]
          - id: check-ast
          - id: debug-statements
          - id: detect-private-key
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.5.0
      hooks:
          - id: ruff
            args: [--fix, --exit-non-zero-on-fix]
          - id: ruff-format
