name: Create Release Tag

on:
  pull_request:
    types: [ closed ]
    branches: [ master ]

jobs:
  tag-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Bump version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_annotated_tag: true

      - name: Echo new tag
        run:
          echo "Nova tag: ${{ steps.tag_version.outputs.new_tag }}"
