name: Create Release Tag

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  tag-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fetch_all_tags: true
          create_annotated_tag: true

      - name: Show new tag
        run: |
          echo "Nova tag: ${{ steps.tag_version.outputs.new_tag }}"
