name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Update version in pyproject.toml
        run: |
          TAG_VERSION=${GITHUB_REF_NAME#v}
          sed -i "s/^version = \".*\"/version = \"${TAG_VERSION}\"/" pyproject.toml

      - name: Build package
        run: |
          python -m pip install --upgrade pip build
          python -m build

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
