name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Update version
        run: |
          TAG_VERSION=${GITHUB_REF_NAME#v}
          sed -i "s/^version = \".*\"/version = \"${TAG_VERSION}\"/" pyproject.toml

      - name: Commit version
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add pyproject.toml
          git commit -m "chore(release): update version to ${TAG_VERSION} [skip ci]" || true
          git push origin master || true

      - name: Build package
        run: |
          python -m pip install --upgrade pip build twine
          python -m build

      - uses: pypa/gh-action-pypi-publish@release/v1
