name: Publish to PyPI

on:
  push:
    branches: [ master ] # Roda quando atualiza a master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup do Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar dependências e buildar
        run: |
          python -m pip install --upgrade pip build twine
          python -m build

      - name: Publicar no PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # Token vem dos Secrets do repositório. Nunca colocar direto aqui.
          password: ${{ secrets.PYPI_API_TOKEN }}