name: Release & Publish

on:
  push:
    branches: [ master ]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: 0

      - id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fetch_all_tags: true
          commit_sha: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Show new tag
        run: |
          echo "Nova tag: ${{ steps.tag_version.outputs.new_tag }}"

      - name: Update version in pyproject.toml
        run: |
          TAG_VERSION="${{ steps.tag_version.outputs.new_tag }}"
          TAG_VERSION="${TAG_VERSION#v}"
          sed -i -E 's/^[[:space:]]*version[[:space:]]*=[[:space:]]*".*"/version = "'"$TAG_VERSION"'"/' pyproject.toml

      - name: Commit version bump
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add pyproject.toml
          git commit -m "chore(release): set version to $TAG_VERSION [skip ci]" || true
          git push origin HEAD:refs/heads/master

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Build package
        run: |
          python -m pip install --upgrade pip build
          python -m build

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          attestations: true
